TARGET = iphone:clang:14.5:11.0

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = AmberSpringBoard
$(TWEAK_NAME)_FILES = AmberSpringBoard.x
$(TWEAK_NAME)_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
