ARCHS = arm64

include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Amber
Amber_FILES = Switch.xm
Amber_LIBRARIES = flipswitch
Amber_FRAMEWORKS = UIKit
Amber_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk